### ISSUE TITLE
Not working with some soundpacks

### ISSUE THREAD

**Issue by bhattkacode** [KunalBagaria/rustyvibes#30]
I downloaded soundpack "Akko Lavenders" from the [mechvibes custom soundpacks](https://docs.google.com/spreadsheets/d/1jSVTHxTefzqodzupgzDw8e6yXAFX84fCCsAWvP0U5tA/edit#gid=160591801).
It had same structure of other soundpacks with works with rustyvibes (sound files and config.json) but it didn't work
I converted all mp3 files to wav, and changed config.json to match it. still didnt worked. It gives error:
```Soundpack configuration loaded
Rustyvibes is running
fALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
thread '<unnamed>' panicked at /home/sahaj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyvibes-1.0.9/src/play_sound.rs:53:82:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
gALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
thread '<unnamed>' panicked at /home/sahaj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyvibes-1.0.9/src/play_sound.rs:49:60:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }

**Comment by Redoxahmii** [comment]
> I downloaded soundpack "Akko Lavenders" from the [mechvibes custom soundpacks](https://docs.google.com/spreadsheets/d/1jSVTHxTefzqodzupgzDw8e6yXAFX84fCCsAWvP0U5tA/edit#gid=160591801). It had same structure of other soundpacks with works with rustyvibes (sound files and config.json) but it didn't work I converted all mp3 files to wav, and changed config.json to match it. still didnt worked. It gives error:
> 
> ```
> Rustyvibes is running
> fALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
> thread '<unnamed>' panicked at /home/sahaj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyvibes-1.0.9/src/play_sound.rs:53:82:
> called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> gALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
> thread '<unnamed>' panicked at /home/sahaj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyvibes-1.0.9/src/play_sound.rs:49:60:
> called `Result::unwrap()` on an `Err` value: PoisonError { .. }
> ```

Even found a solution to this ? I am using eg oreo and the developer seems to have abandoned this project.

**Comment by KunalBagaria** [comment]
Hey, I've shifted focus from the project, but feel free to take over if you're keen on fixing. Cheers!

**Comment by Redoxahmii** [comment]
> Hey, I've shifted focus from the project, but feel free to fork and take over if you're keen on fixing. Cheers!

That's sad i would have loved to try to keep this project alive but i have never worked with rust.
