### ISSUE TITLE
The app crashing after pressing certain keys 

### ISSUE THREAD

**Issue by spurjhattam2207** [KunalBagaria/rustyvibes#32]
The program works perfectly with all keys except one(in MacOS) that is the esc key. As soon as one presses the esc key,

`thread '<unnamed>' panicked at /Users/purushottamsharma/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyvibes-1.0.9/src/play_sound.rs:53:82: called Result::unwrap()on anErrvalue: Os { code: 2, kind: NotFound, message: "No such file or directory" } note: run withRUST_BACKTRACE=1environment variable to display a backtrace thread '<unnamed>' panicked at /Users/purushottamsharma/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyvibes-1.0.9/src/play_sound.rs:49:60: calledResult::unwrap()on anErr value: PoisonError { .. }`

such errors pop up and no further key press produces any sound.

**Comment by KunalBagaria** [comment]
might be an issue with a particular soundpack, "esc" key seems to be working for me with the soundpack I use

**Comment by spurjhattam2207** [comment]
Can you please tell a fix for it? I am using the cherrymx-blue-pbt sound pack.
